### ISSUE TITLE
Icedtea-Web error with percent Width and/or Height value

### ISSUE THREAD

**Issue by patris70** [ojdkbuild/ojdkbuild#101]
Hi,

Icedtea-Web has problem, if Width or/and Height has percent Value in JNLP File.
For example => width="100%" height="1024"

Error detail:

[net.sourceforge.jnlp.AbstractLaunchHandler.printMessage(AbstractLaunchHandler.java:68)] NETX Thread# 1496d9f, name main: net.sourceforge.jnlp.LaunchException: Fatal: Read error: Could not read the JNLP file or parse the syntax. The file may be downloaded manually and sent as an error report to the IcedTea Web Team.
at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)     
at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)     
at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)     
at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)     
at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)     
at java.security.AccessController.doPrivileged(Native Method)     
at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210) Caused by: net.sourceforge.jnlp.ParseException: MALFORMED MALFORMED; Invalid applet width.     
at net.sourceforge.jnlp.Parser.getApplet(Parser.java:758)     
at net.sourceforge.jnlp.Parser.getLauncher(Parser.java:718)     
at net.sourceforge.jnlp.JNLPFile.parse(JNLPFile.java:878)     
at net.sourceforge.jnlp.JNLPFile.(JNLPFile.java:233)     
at net.sourceforge.jnlp.JNLPFile.(JNLPFile.java:215)     
at net.sourceforge.jnlp.JNLPFile.(JNLPFile.java:200)     
at net.sourceforge.jnlp.JNLPFile.(JNLPFile.java:186)     
at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)

Best regars

**Comment by ojdkbuild** [comment]
[Added a fix](https://github.com/ojdkbuild/lookaside_icedtea-web/commit/09a113ec293f7c96c6f500af097ec569bc052fcc), it doesn't attempt to actually compute the specified percents from screen dimensions - uses sane default values instead. It is going to be included into 8u232 build.

**Comment by ojdkbuild** [comment]
Fixed in 8u232, closing the issue.
