### ISSUE TITLE
SunTls12MasterSecret KeyGenerator not available

### ISSUE THREAD

**Issue by burMob** [ojdkbuild/ojdkbuild#85]
Hello,

I've used "java-1.8.0-openjdk-1.8.0.212-1.b04.ojdkbuild.windows.x86_64.msi" and one App is not working.

This is the error message:
java.security.ProviderException: java.security.NoSuchAlgorithmException: SunTls12MasterSecret KeyGenerator not available
os.name=Windows 10
os.version=10.0
java.vm.vendor=
java.vm.version=25.212-b04

Is there something deactivated in the package?

br

**Comment by ojdkbuild** [comment]
Hi, this may be related (hard to tell without full stack trace) to the reduced set of Elliptic Crypto Named Curves - ojdkbuild uses the same set that is used in RHEL 7. Please see details: [issue](https://github.com/ojdkbuild/ojdkbuild/issues/11), [maillist thread](https://groups.google.com/d/msg/ojdkbuild/yptKbWPFBA4/jGWTv27DBwAJ).

**Comment by burMob** [comment]
this is all we get from the error:

javax.net.ssl.SSLException: java.security.ProviderException: java.security.NoSuchAlgorithmException: SunTls12MasterSecret KeyGenerator not available
                at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
                at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
                at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1903)
                at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1886)
                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1402)
                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
                at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
                at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
                at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
                at com.asap.dragon.client.wrapper.ServletHandler.connectToServlet0(ServletHandler.java:809)
                at com.asap.dragon.client.wrapper.ServletHandler.connectToServlet(ServletHandler.java:752)
                at com.asap.dragon.client.wrapper.ServletHandler.communicate(ServletHandler.java:529)
                at com.asap.dragon.client.wrapper.ServletHandler.communicate(ServletHandler.java:507)
                at com.asap.dragon.client.wrapper.ServletHandler.connectToServer(ServletHandler.java:216)
                at com.asap.dragon.client.wrapper.EJBWrapper.connectToServer(EJBWrapper.java:93)
                at com.asap.dragon.client.jgoodies.desktop.LoginProcessor.connectToServer(LoginProcessor.java:209)
                at com.asap.dragon.client.jgoodies.desktop.LoginProcessor.connectAndCheckLogin(LoginProcessor.java:186)
                at com.asap.dragon.client.jgoodies.desktop.LoginProcessor.access$300(LoginProcessor.java:88)
                at com.asap.dragon.client.jgoodies.desktop.LoginProcessor$LoginWorker.construct(LoginProcessor.java:972)
                at com.asap.dragon.client.wait.WaitWorker.lambda$new$1(WaitWorker.java:77)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.ProviderException: java.security.NoSuchAlgorithmException: SunTls12MasterSecret KeyGenerator not available
                at sun.security.ssl.Handshaker.calculateMasterSecret(Handshaker.java:1278)
                at sun.security.ssl.Handshaker.calculateKeys(Handshaker.java:1188)
                at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1133)
                at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:369)
                at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
                at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
                at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
                at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
                ... 19 more
Caused by: java.security.NoSuchAlgorithmException: SunTls12MasterSecret KeyGenerator not available
                at javax.crypto.KeyGenerator.<init>(KeyGenerator.java:169)
                at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:223)
                at sun.security.ssl.JsseJce.getKeyGenerator(JsseJce.java:251)
                at sun.security.ssl.Handshaker.calculateMasterSecret(Handshaker.java:1265)
                ... 27 more

**Comment by rmgarg22** [comment]
@burMob How was this resolved?

**Comment by burMob** [comment]
I've changed the product ...

**Comment by ojdkbuild** [comment]
This should no longer be the case for both CentOS ([[1]](https://git.centos.org/rpms/java-1.8.0-openjdk/c/5554713931c27563d2d75a5252f099431ce2e773?branch=c7), [[2]](https://git.centos.org/rpms/java-1.8.0-openjdk/c/d31e8d27d7873411a29e850295324320c5fde754?branch=c7)) and Windows - all EC curves are included now.
